import { Inter } from 'next/font/google'
import './globals.css'

import Navbar from '@/components/navbar'

// Tanstack React Query Provider
import {TanstackProvider} from './../providers/tanstackprovider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <TanstackProvider>
        <Navbar />
        {children}
      </TanstackProvider>
      </body>
    </html>
  )
}
