import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// 2.5. Pasang Tanstack Provider
import { TanstackProvider } from '@/providers/tanstackProvider'

import Navbar from '@/components/navbar';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
        <Navbar />
        {children}
        </TanstackProvider>
      </body>
    </html>
  )
}
